### PR TITLE
Added Contact Us Page

### PR DESCRIPTION
**Pull request by TheFirstMe**
This is a fix for #19

### CODE REVIEW

**Comment by TheFirstMe** [comment]
I noticed that the privacy link in the footer was changed to the anchor tag from the core Link component. Was this expected?

**Comment by arshadkazmi42** [comment]
> I noticed that the privacy link in the footer was changed to the anchor tag from the core Link component. Was this expected?

Good catch. I am not sure, which commit change that, but we want to keep it as Link. 
Also can you add snapshot of the contact page in this PR

**Comment by TheFirstMe** [comment]
snip png
Here's the snapshot of the contact page. Please let me know if any changes are to be made.

**Comment by arshadkazmi42** [comment]
@TheFirstMe Good work.
But the page looks very empty, any suggestions if we can add anything else in the page?
I am checking if I can get some design out for this

**Comment by TheFirstMe** [comment]
@arshadkazmi42 I think a contact form would be a nice addition.

**Comment by sinumohan** [comment]
Can we add github also? Link: https://github.com/unauthapp

**Comment by arshadkazmi42** [comment]
> @arshadkazmi42 I think a contact form would be a nice addition.

We don't have backend yet to support forms. I will work on getting some design

**Comment by TheFirstMe** [comment]
> Can we add github also? Link: https://github.com/unauthapp

snip2

Done.

**Comment by TheFirstMe** [comment]
I also changed the Privacy Policy text back to the Link component. But the text was printing in the next line. The core Link component has a StyledText div as a child. This causes that unexpected new line. For the time being, I added a display prop to Link which I set to inline to solve the issue. 

snip3

This is how it looks if the Link component is used as is.

**Comment by sinumohan** [comment]
for the contact us form there is a new issue created

**Pull request merged**
