### PR TITLE
added social links

### LINKED ISSUE #20: Add social media links &  email on footer
**Add footer buttons with following button links**
------------------------------------------
FB: https://www.facebook.com/unauthapp
Twitter: https://twitter.com/unauthapp
Email: unauth.cloud@gmail.com

### PR DESCRIPTION
**Pull request by AlexanderMalmstrom**
This fixes #20

### CODE REVIEW

**Comment by sinumohan** [comment]
Good job @AlexanderMalmstrom, I ran into a babel version issue while testing it, had to use `SKIP_PREFLIGHT_CHECK=true` to run it. I will merge this after verifying it.

**Comment by arshadkazmi42** [comment]
There are few warnings in console also, can you also work on fixing those
Screen Shot 2019-10-26 at 9 22 28 AM

**Comment by AlexanderMalmstrom** [comment]
@arshadkazmi42 I have fixed the errors and removed som margins.

image

**Comment by arshadkazmi42** [comment]
@AlexanderMalmstrom can we remove some margin between Copyright text and privacy policy

**Comment by AlexanderMalmstrom** [comment]
@arshadkazmi42 something like this maybe?

image

**Comment by arshadkazmi42** [comment]
Thanks @AlexanderMalmstrom 
I have updated the PR with some minor changes. Here is it, how it looks

Screen Shot 2019-10-26 at 4 43 35 PM

**Pull request merged**
