### PR TITLE
added github link

### PR DESCRIPTION
**Pull request by SafaElmali**

### CODE REVIEW

**Comment by arshadkazmi42** [comment]
Can you add snapshot after the changes

**Comment by SafaElmali** [comment]
> Can you add snapshot after the changes

Sure. There you go.

Screenshot 2019-10-27 at 13 55 56

**Comment by SafaElmali** [comment]
> Can you remove `package-lock.json` file. We use `yarn`

Yes of course!

**Comment by arshadkazmi42** [comment]
Thank you for taking this up

**Comment by SafaElmali** [comment]
> Thank you for taking this up

You're welcome :)

**Comment by sinumohan** [comment]
@SafaElmali @arshadkazmi42 deployed 👍

**Pull request merged**
